name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3  # Use the latest version
        with:
          github_user_name: "Adilsheikhh"  # Ensure this is your actual GitHub username
          outputs: dist/snake.svg

      - name: Commit and Push
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/snake.svg
